# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false

controller_frequency: 1.0
controller_patience: 0.02

# planner_frequency: 1.0
# planner_patience: 5.0

# oscillation_timeout: 10.0
# oscillation_distance: 0.2

# yaw_goal_tolerance: 1   # earlier 1.0
# xy_goal_tolerance: 1

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"

dwa_local_planner's forward_point_distance: 0